FROM amazoncorretto:21-alpine-jdk
WORKDIR /app
COPY target/smeshariki-back-0.0.1-SNAPSHOT.war /app/smeshariki-back-0.0.1-SNAPSHOT.war
EXPOSE 8081
CMD ["java", "-jar", "/app/smeshariki-back-0.0.1-SNAPSHOT.war"]